POST http://localhost:8080/create-quizroom
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE1NjM5MjQsInVzZXJfaWQiOjIsInVzZXJuYW1lIjoidGVzdCJ9.5iEgEVz7Lcn0VC9ZpXyTEmSiB1vD_30oyvaN3k9KAfs  

  {
      "Players": [{
        "PlayerId": 111,
        "Username": "111"
      }],
      "TimerTime": 5,
      "QuizTopic": "science",
      "PlayersAnswers": {"0": "10",
                         "1": "false"}
    }
