GET http://localhost:8080/quizrooms/4/2/answer
Content-Type : application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDg2MzMwMTQsInVzZXJfaWQiOjIsInVzZXJuYW1lIjoidGVzdDIifQ.ZNJo-plE8YSk1rFFsD4gO2Bb3UnLGFrOtaHJcbe5J00